feat(MembershipsAdapter): add addMembersToRoom method
webex/component-adapter-interfaces pull request #90
Opened 2022-03-18 15:13 UTC by harsh789rai

add an addMembersToRoom method to MembershipsAdapter to add a member in the room for the given room id.

2022-03-19 04:53 UTC, kishorepmr requested changes

2022-03-19 04:53 UTC, kishorepmr commented on src/MembershipsAdapter.js
> +   * Add members to room for the given room id.Returns an observable
* Add members to the given room. 

Move the **Returns an observable that emits the Member array.** to next line

2022-03-19 04:53 UTC, kishorepmr commented on src/MembershipsAdapter.js
> +   * @param {string} roomId Room id in which members are to be added
roomId -> roomID

and description also **ID of the room where members are to be added.**

2022-03-19 04:53 UTC, kishorepmr commented on src/MembershipsAdapter.js
> +   * @param {Array} roomMembers Emails of person to be added in room for the given room id
@harsh789rai the create membership of JS SDK accepts email as well as person ID as well.

I think the parameter should be Array of Member object or Person Object.

2022-03-19 04:53 UTC, kishorepmr commented on src/MembershipsAdapter.js
> +   * @returns {Observable<Member[]>} Observable that emits data after members added to room
Observable stream that emits member data.

2022-03-22 05:57 UTC, harsh789rai commented on src/MembershipsAdapter.js
> +   * @returns {Observable<Member[]>} Observable that emits data after members added to room
All the changes addressed

2022-03-31 21:19 UTC, lalli-flores commented
@harsh789rai , @kishorepmr Team added similar definitions in https://github.com/webex/component-adapter-interfaces/pull/93

2022-03-31 21:19 UTC, closed without merging